# Generated by Django 4.2.16 on 2025-07-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0011_customer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaincategory',
            name='cat_image_url',
            field=models.URLField(blank=True, help_text='Optional. You can provide a URL to an image instead of uploading a file.', max_length=500, null=True),
        ),
    ]
