# Generated by Django 4.2.16 on 2025-07-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0013_product_product_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsubcategory',
            options={'verbose_name_plural': 'Sub Product Categories'},
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='sub_cat_image_url',
            field=models.URLField(blank=True, help_text='Optional. You can provide a URL to an image instead of uploading a file.', max_length=500, null=True),
        ),
    ]
